name: Deploy Expo Web App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Explicitly forces the runner to handle all compilation on Node 24
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6 # Native Node 24 version

      - name: Setup Node.js
        uses: actions/setup-node@v6 # Native Node 24 version
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Build Web Application
        run: npm run build:web

      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web-build
          branch: gh-pages
